#!/usr/bin/env python3

import argparse
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT / "python"
if str(PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(PYTHON_DIR))

from dae.op_families import gemv_family_spec_by_name, is_registered_family_name, validate_family_name


DISPATCH_PATTERN = re.compile(r"^\s*DAE_COMPUTE_OP_HANDLER\(\s*([A-Za-z0-9_]+)\s*\)\s*\{?\s*$")
OPCODE_PATTERN = re.compile(r"^\s*DAE_OP\(\s*([A-Za-z0-9_]+)\s*,\s*(.+?)\s*\)\s*(?://.*)?$")
DEFAULT_COMPUTE_OPS_FILE = "dae_compute_ops.vdcore.build"
COMPUTE_OPS_ENV = "DAE_COMPUTE_OPS"
COMPUTE_OPS_FILE_ENV = "DAE_COMPUTE_OPS_FILE"
COMPUTE_OPCODE_BASE = 0x7000


def load_supported_compute_ops(path: Path) -> list[str]:
    entries: list[str] = []
    for raw_line in path.read_text().splitlines():
        line = raw_line.split("//", 1)[0].strip()
        if not line:
            continue
        match = DISPATCH_PATTERN.match(line)
        if match is None:
            continue
        entries.append(match.group(1))
    if not entries:
        raise ValueError(f"No compute-op handlers found in {path}")
    return entries


def load_all_compute_ops(path: Path) -> list[str]:
    entries: list[str] = []
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line:
            continue
        match = OPCODE_PATTERN.match(line)
        if match is not None:
            name, value = match.groups()
            if "MK_MOP" in value:
                continue
            entries.append(name)
            continue

    if not entries:
        raise ValueError(f"No compute opcodes found in {path}")
    return entries


def parse_operator_list(text: str) -> list[str]:
    names: list[str] = []
    seen: set[str] = set()
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0]
        for item in line.split(","):
            name = item.strip()
            if not name or name in seen:
                continue
            names.append(name)
            seen.add(name)
    return names


def resolve_requested_ops(base_dir: Path) -> tuple[list[str] | None, str]:
    if COMPUTE_OPS_ENV in os.environ:
        requested_ops = parse_operator_list(os.environ.get(COMPUTE_OPS_ENV, ""))
        if requested_ops:
            return requested_ops, f"env:{COMPUTE_OPS_ENV}"
        return None, f"env:{COMPUTE_OPS_ENV}:full"

    if COMPUTE_OPS_FILE_ENV in os.environ:
        requested_ops_file = Path(os.environ[COMPUTE_OPS_FILE_ENV]).expanduser()
        if not requested_ops_file.is_absolute():
            requested_ops_file = base_dir / requested_ops_file
        if not requested_ops_file.exists():
            raise ValueError(f"Compute-op file {requested_ops_file} from {COMPUTE_OPS_FILE_ENV} does not exist")
        return parse_operator_list(requested_ops_file.read_text()), f"file:{requested_ops_file}"

    default_ops_file = base_dir / DEFAULT_COMPUTE_OPS_FILE
    if default_ops_file.exists():
        return parse_operator_list(default_ops_file.read_text()), f"file:{default_ops_file}"

    return None, "default:full"


def parse_dynamic_operator(name: str) -> dict[str, int | str] | None:
    if not is_registered_family_name(name):
        return None

    canonical_name = validate_family_name(name)
    spec = gemv_family_spec_by_name(canonical_name)
    if spec is not None:
        return spec

    raise ValueError(f"Malformed dynamic compute-op family string: {canonical_name}")


def select_entries(supported_ops: list[str], requested_ops: list[str] | None) -> tuple[list[str], list[dict[str, int | str]]]:
    if requested_ops is None:
        return supported_ops, []

    selected_names: list[str] = []
    dynamic_entries: list[dict[str, int | str]] = []
    supported_name_set = set(supported_ops)
    for name in requested_ops:
        dynamic_entry = parse_dynamic_operator(name)
        if dynamic_entry is not None:
            selected_names.append(dynamic_entry["name"])
            dynamic_entries.append(dynamic_entry)
            continue
        if name not in supported_name_set:
            valid_names = ", ".join(sorted(supported_ops))
            raise ValueError(f"Unknown compute operator {name!r}. Valid compute operators: {valid_names}")
        selected_names.append(name)
    return selected_names, dynamic_entries


def build_opcode_order(all_compute_ops: list[str], selected_ops: list[str], dynamic_entries: list[dict[str, int | str]]) -> list[str]:
    selected_set = set(selected_ops)
    dynamic_names = [entry["name"] for entry in dynamic_entries]
    remaining_ops = [name for name in all_compute_ops if name not in selected_set]
    remaining_ops = [name for name in remaining_ops if name not in dynamic_names]
    return [*selected_ops, *remaining_ops]


def write_selection(path: Path, entries: list[str], source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "// Generated by tools/generate_selected_compute_ops.py.",
        f"// source={source}",
        "",
    ]
    body = [f"DAE_COMPUTE_OP({name})" for name in entries]
    path.write_text("\n".join(header + body + [""]))


def write_opcode_order(path: Path, entries: list[str], source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "// Generated by tools/generate_selected_compute_ops.py.",
        f"// source={source}",
        f"// base=0x{COMPUTE_OPCODE_BASE:04x}",
        "",
    ]
    body = [
        f"DAE_COMPUTE_OPCODE({name}, 0x{COMPUTE_OPCODE_BASE + index:04x})"
        for index, name in enumerate(entries)
    ]
    path.write_text("\n".join(header + body + [""]))


def render_dynamic_handler(entry: dict[str, int | str]) -> str:
    name = entry["name"]
    if not entry["family"].startswith("gemv_"):
        raise ValueError(f"Unsupported dynamic family in code generation: {entry['family']}")

    prelude = [
        f"DAE_COMPUTE_OP_HANDLER({name}) {{",
        "  DAE_UNUSED(sm_id, thread_id, pc, count, finish, scratch_space, st_insts, g_events);",
    ]
    if entry["family"] == "gemv_wgmma":
        body = [
            "  using gemv_atom = cute::SM90_64x8x16_F32BF16BF16_SS<cute::GMMA::Major::K, cute::GMMA::Major::K>;",
            (
                f"  task_gemv<gemv_atom, {entry['m']}, {entry['k']}, {entry['bload']}, false>"
                "(inst.args[0], inst.args[1], smem_base, m2c, c2m);"
            ),
        ]
    elif entry["family"] == "gemv_mma":
        body = [
            f"  task_gemv_mma<{entry['m']}, {entry['n']}, {entry['k']}>(inst.args[0], smem_base, m2c, c2m);",
        ]
    else:
        raise ValueError(f"Unsupported GEMV family in code generation: {entry['family']}")
    return "\n".join(prelude + body + ["}"])


def write_dynamic_handlers(path: Path, entries: list[dict[str, int | str]], source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "// Generated by tools/generate_selected_compute_ops.py.",
        f"// source={source}",
        "",
    ]
    body = [render_dynamic_handler(entry) for entry in entries]
    path.write_text("\n\n".join(header + body + [""]))


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the selected compute-op include used by the build.")
    parser.add_argument("--dispatch", required=True, help="Path to compute_dispatch.cuh")
    parser.add_argument("--opcode-registry", required=True, help="Path to opcode.cuh.inc")
    parser.add_argument("--output", required=True, help="Path to the generated selected-op include")
    parser.add_argument("--opcode-output", required=True, help="Path to the generated compute-opcode-order include")
    parser.add_argument("--dynamic-handlers-output", required=True, help="Path to the generated dynamic compute-handler include")
    args = parser.parse_args()

    try:
        dispatch_path = Path(args.dispatch)
        opcode_registry_path = Path(args.opcode_registry)
        output_path = Path(args.output)
        opcode_output_path = Path(args.opcode_output)
        dynamic_handlers_output_path = Path(args.dynamic_handlers_output)
        requested_ops, source = resolve_requested_ops(Path.cwd())

        supported_ops = load_supported_compute_ops(dispatch_path)
        all_compute_ops = load_all_compute_ops(opcode_registry_path)
        selected, dynamic_entries = select_entries(supported_ops, requested_ops)
        opcode_order = build_opcode_order(all_compute_ops, selected, dynamic_entries)
        write_selection(output_path, selected, source)
        write_opcode_order(opcode_output_path, opcode_order, source)
        write_dynamic_handlers(dynamic_handlers_output_path, dynamic_entries, source)
        print(
            f"[compute-ops] source={source} selected={len(selected)} "
            f"dynamic={len(dynamic_entries)} all_compute={len(opcode_order)}"
        )
    except ValueError as exc:
        parser.exit(1, f"{exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
