#!/usr/bin/env python3

import argparse
import os
import re
from pathlib import Path


DISPATCH_PATTERN = re.compile(r"^\s*DAE_COMPUTE_OP_HANDLER\(\s*([A-Za-z0-9_]+)\s*\)\s*\{?\s*$")
DEFAULT_COMPUTE_OPS_FILE = "dae_compute_ops.vdcore.build"
COMPUTE_OPS_ENV = "DAE_COMPUTE_OPS"
COMPUTE_OPS_FILE_ENV = "DAE_COMPUTE_OPS_FILE"


def load_supported_compute_ops(path: Path) -> list[str]:
    entries: list[str] = []
    for raw_line in path.read_text().splitlines():
        line = raw_line.split("//", 1)[0].strip()
        if not line:
            continue
        match = DISPATCH_PATTERN.match(line)
        if match is None:
            continue
        entries.append(match.group(1))
    if not entries:
        raise ValueError(f"No compute-op handlers found in {path}")
    return entries


def parse_operator_list(text: str) -> list[str]:
    names: list[str] = []
    seen: set[str] = set()
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0]
        for item in line.split(","):
            name = item.strip()
            if not name or name in seen:
                continue
            names.append(name)
            seen.add(name)
    return names


def resolve_requested_ops(base_dir: Path) -> tuple[list[str] | None, str]:
    if COMPUTE_OPS_ENV in os.environ:
        requested_ops = parse_operator_list(os.environ.get(COMPUTE_OPS_ENV, ""))
        if requested_ops:
            return requested_ops, f"env:{COMPUTE_OPS_ENV}"
        return None, f"env:{COMPUTE_OPS_ENV}:full"

    if COMPUTE_OPS_FILE_ENV in os.environ:
        requested_ops_file = Path(os.environ[COMPUTE_OPS_FILE_ENV]).expanduser()
        if not requested_ops_file.is_absolute():
            requested_ops_file = base_dir / requested_ops_file
        if not requested_ops_file.exists():
            raise ValueError(f"Compute-op file {requested_ops_file} from {COMPUTE_OPS_FILE_ENV} does not exist")
        return parse_operator_list(requested_ops_file.read_text()), f"file:{requested_ops_file}"

    default_ops_file = base_dir / DEFAULT_COMPUTE_OPS_FILE
    if default_ops_file.exists():
        return parse_operator_list(default_ops_file.read_text()), f"file:{default_ops_file}"

    return None, "default:full"


def select_entries(supported_ops: list[str], requested_ops: list[str] | None) -> list[str]:
    if requested_ops is None:
        return supported_ops

    selected_names: list[str] = []
    for name in requested_ops:
        if name not in supported_ops:
            valid_names = ", ".join(sorted(supported_ops))
            raise ValueError(f"Unknown compute operator {name!r}. Valid compute operators: {valid_names}")
        selected_names.append(name)
    selected_name_set = set(selected_names)
    return [name for name in supported_ops if name in selected_name_set]


def write_selection(path: Path, entries: list[str], source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "// Generated by tools/generate_selected_compute_ops.py.",
        f"// source={source}",
        "",
    ]
    body = [f"DAE_COMPUTE_OP({name})" for name in entries]
    path.write_text("\n".join(header + body + [""]))


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the selected compute-op include used by the build.")
    parser.add_argument("--dispatch", required=True, help="Path to compute_dispatch.cuh")
    parser.add_argument("--output", required=True, help="Path to the generated selected-op include")
    args = parser.parse_args()

    try:
        dispatch_path = Path(args.dispatch)
        output_path = Path(args.output)
        requested_ops, source = resolve_requested_ops(Path.cwd())

        supported_ops = load_supported_compute_ops(dispatch_path)
        selected = select_entries(supported_ops, requested_ops)
        write_selection(output_path, selected, source)
        print(f"[compute-ops] source={source} selected={len(selected)}")
    except ValueError as exc:
        parser.exit(1, f"{exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
